spring.application.name=cxp-ordermanagement-domain
server.port=8092
server.shutdown=graceful
management.endpoints.web.exposure.include=*
management.info.git.mode=full
####  This will include the java version and jvm information in the actuator/info  #########
#management.info.java.enabled=true


catalog.page-size=10

######## Database Configuration  #########
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:25432/postgres}
#spring.datasource.url=jdbc:postgresql://localhost:15432/postgres
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

######## RabbitMQ Configuration  #########
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

######## Flyway Migration Configuration  #########
spring.flyway.clean-on-validation-error = true
spring.flyway.clean-disabled = false
spring.flyway.locations=classpath:db/migration
spring.flyway.baselineOnMigrate = true