spring.application.name=cxp-ordermanagement-domain
server.port=8092
server.shutdown=graceful
management.endpoints.web.exposure.include=*
management.info.git.mode=full
####  This will include the java version and jvm information in the actuator/info  #########
#management.info.java.enabled=true


######## Order Service Configuration  #########
orders.order-events-exchange=orders-exchange
orders.new-orders-queue=new-orders
orders.delivered-orders-queue=delivered-orders
orders.cancelled-orders-queue=cancelled-orders
orders.error-orders-queue=error-orders

######## Database Configuration  #########
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:25432/postgres}
#spring.datasource.url=jdbc:postgresql://localhost:15432/postgres
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.open-in-view=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

######## RabbitMQ Configuration  #########
#spring.rabbitmq.host=${RABBITMQ_HOST:easyshop-rabbitmq}
#spring.rabbitmq.port=${RABBITMQ_PORT:15672}
#spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
#spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
#spring.rabbitmq.connection-timeout=5000
#spring.rabbitmq.template.retry.enabled=true
#spring.rabbitmq.template.retry.initial-interval=2000
#spring.rabbitmq.template.retry.max-attempts=3
#spring.rabbitmq.template.retry.max-interval=10000
#spring.rabbitmq.listener.simple.retry.enabled=true
#spring.rabbitmq.listener.simple.retry.initial-interval=2000
#spring.rabbitmq.listener.simple.retry.max-attempts=3
#spring.rabbitmq.listener.simple.retry.max-interval=10000

######## Flyway Migration Configuration  #########
spring.flyway.clean-on-validation-error = true
spring.flyway.clean-disabled = false
spring.flyway.locations=classpath:db/migration
spring.flyway.baselineOnMigrate = true