name: 'easyshop'
services:
    cxp-catalog-domain:
      image: kishore465/easyshop-cxp-catalog-domain
      container_name: cxp-catalog-domain
      environment:
        - SPRING_PROFILES_ACTIVE=docker
        - DB_URL=jdbc:postgresql://catalog-db:5432/postgres
        - DB_USERNAME=postgres
        - DB_PASSWORD=postgres
        - JVM_OPTS=-Xmx2g -Xms2g -XX:MaxPermSize=1024m
        - SWAGGER_API_GATEWAY_URL=http://api-gateway:8989/catalog
        - MANAGEMENT_TRACING_ENABLED=${MANAGEMENT_TRACING_ENABLED}
        - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
#        - CATALINA_OPTS=-Xmx12g -Xms12g -XX:MaxPermSize=1024m
      ports:
        - "8091:8091"
      restart: unless-stopped
      depends_on:
        catalog-db:
          condition: service_healthy
      deploy:
        resources:
          limits:
            memory: 2g
      labels:
        logging: "promtail"
    cxp-ordermanagement-domain:
      image: kishore465/easyshop-cxp-ordermanagement-domain
      container_name: cxp-ordermanagement-domain
      environment:
        - SPRING_PROFILES_ACTIVE=docker
        - ORDERS_CATALOG_DOMAIN_URL=http://api-gateway:8989/catalog
        - DB_URL=jdbc:postgresql://orders-db:5432/postgres
        - DB_USERNAME=postgres
        - DB_PASSWORD=postgres
        - RABBITMQ_HOST=easyshop-rabbitmq
        - RABBITMQ_PORT=5672
        - RABBITMQ_USERNAME=guest
        - RABBITMQ_PASSWORD=guest
        - JVM_OPTS=-Xmx2g -Xms2g -XX:MaxPermSize=1024m
        - SWAGGER_API_GATEWAY_URL=http://api-gateway:8989/orders
        - MANAGEMENT_TRACING_ENABLED=${MANAGEMENT_TRACING_ENABLED}
        - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
#        - CATALINA_OPTS=-Xmx2g -Xms2g -XX:MaxPermSize=1024m
      ports:
        - "8092:8092"
      restart: unless-stopped
      depends_on:
        orders-db:
          condition: service_healthy
        easyshop-rabbitmq:
          condition: service_healthy
      deploy:
        resources:
          limits:
            memory: 2g
      labels:
        logging: "promtail"
    cxp-notification-domain:
      image: kishore465/easyshop-cxp-notification-domain
      container_name: cxp-notification-domain
      environment:
        - SPRING_PROFILES_ACTIVE=docker
        - DB_URL=jdbc:postgresql://notifications-db:5432/postgres
        - DB_USERNAME=postgres
        - DB_PASSWORD=postgres
        - RABBITMQ_HOST=easyshop-rabbitmq
        - RABBITMQ_PORT=5672
        - RABBITMQ_USERNAME=guest
        - RABBITMQ_PASSWORD=guest
        - MAIL_HOST=mailhog
        - MAIL_PORT=1025
        - JVM_OPTS=-Xmx2g -Xms2g -XX:MaxPermSize=1024m
        - MANAGEMENT_TRACING_ENABLED=${MANAGEMENT_TRACING_ENABLED}
        - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
      #        - CATALINA_OPTS=-Xmx2g -Xms2g -XX:MaxPermSize=1024m
      ports:
        - "8093:8093"
      restart: unless-stopped
      depends_on:
        notifications-db:
          condition: service_healthy
        easyshop-rabbitmq:
          condition: service_healthy
        mailhog:
          condition: service_started
      deploy:
        resources:
          limits:
            memory: 2g
      labels:
        logging: "promtail"
    api-gateway:
      image: kishore465/easyshop-api-gateway
      container_name: api-gateway
      environment:
        - SPRING_PROFILES_ACTIVE=docker
        - CATALOG_SERVICE_URL=http://cxp-catalog-domain:8091
        - ORDER_SERVICE_URL=http://cxp-ordermanagement-domain:8092
        - MANAGEMENT_TRACING_ENABLED=${MANAGEMENT_TRACING_ENABLED}
        - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
      ports:
        - "8989:8989"
      restart: unless-stopped
      deploy:
        resources:
          limits:
            memory: 700m
      labels:
        logging: "promtail"
    easyshop-webapp:
      image: kishore465/easyshop-easyshop-webapp
      container_name: easyshop-webapp
      environment:
        - SPRING_PROFILES_ACTIVE=docker
        - BOOKSTORE_API_GATEWAY_URL=http://api-gateway:8989
        - MANAGEMENT_TRACING_ENABLED=${MANAGEMENT_TRACING_ENABLED}
        - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
      ports:
        - "8080:8080"
      restart: unless-stopped
      deploy:
        resources:
          limits:
            memory: 700m
      labels:
        logging: "promtail"
