spring.application.name=cxp-notification-domain
server.port=8093
server.shutdown=graceful

######## Actuator Configuration  #########
management.info.git.mode=full
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.application.name}
management.tracing.enabled=false
management.tracing.sampling.probability=1.0

######## Notification Domain Configuration  #########
notifications.support-email=kishore@gmail.com
notifications.catalog-domain-url=http://localhost:8091
notifications.order-events-exchange=orders-exchange
notifications.new-orders-queue=new-orders
notifications.delivered-orders-queue=delivered-orders
notifications.cancelled-orders-queue=cancelled-orders
notifications.error-orders-queue=error-orders

######## Database Configuration  #########
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:35432/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.open-in-view=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

######## RabbitMQ Configuration  #########
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
#spring.rabbitmq.virtual-host=/
#
## Enable retry mechanism
#spring.rabbitmq.listener.simple.retry.enabled=true
#spring.rabbitmq.listener.simple.retry.initial-interval=2000
#spring.rabbitmq.listener.simple.retry.max-attempts=3
#spring.rabbitmq.listener.simple.retry.max-interval=10000
#
## Connection timeout (in milliseconds)
#spring.rabbitmq.connection-timeout=5000

#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest

############# Mail Properties ###########
spring.mail.host=${MAIL_HOST:127.0.0.1}
spring.mail.port=${MAIL_PORT:1025}
spring.mail.username=${MAIL_USERNAME:PLACEHOLDER}
spring.mail.password=${MAIL_PASSWORD:PLACEHOLDER}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

