name: cxp-catalog-domain

on:
  push:
#    paths:
#      - './cxp-catalog-domain/**'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./cxp-catalog-domain
      DOCKER_IMAGE_NAME: cxp-catalog-domain
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Make Maven wrapper executable
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw -ntp verify

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image with Debug Logs
        run: ./mvnw spring-boot:build-image -DskipTests

      - name: Verify Docker Image
        run: docker images | grep $DOCKER_IMAGE_NAME

      - name: Push Docker Image
        run: |
          echo "Pushing the image $DOCKER_IMAGE_NAME to Docker Hub..."
          docker build -t kishore465/cxp-catalog-domain:latest -f "deployment/docker-compose/infra.yml" .
          docker push cxp-catalog-domain:latest || echo "Docker push failed. Verify that the image exists locally and the name is correct."
#          docker push --all-tags $DOCKER_IMAGE_NAME || echo "Docker push failed. Verify that the image exists locally and the name is correct."
          
